### ISSUE TITLE
Python 3: Traceback occurs when Updating Some Buffers

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#306]
### Steps to reproduce.
Launch TWBlue and try to update some buffers, such as sent tweets.
### Expected.
The buffers update.
### Actual.
TWBlue seems to fail to launch completely and the following traceback is displayed. 
Traceback (most recent call last):
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 72, in <lambda>
    self.parent.Bind(wx.EVT_HOTKEY, lambda evt: self.process_key(evt, key_id), id=key_id)
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 99, in process_key
    self.handle_key(i)
  File "C:\twblue\src\keyboard_handler\main.py", line 47, in handle_key
    return function()
  File "C:\twblue\src\controller\mainController.py", line 1556, in update_buffer
    n = bf.start_stream(mandatory=True, avoid_autoreading=True)
  File "C:\twblue\src\controller\buffers\twitterBuffers.py", line 177, in start_stream
    self.put_items_on_list(number_of_items)
  File "C:\twblue\src\controller\buffers\twitterBuffers.py", line 288, in put_items_on_list
    tweet = self.compose_function(i, self.session.db, self.session.settings["general"]["relative_times"], self.session.s
ettings["general"]["show_screen_names"], self.session)
  File "C:\twblue\src\sessions\twitter\compose.py", line 41, in compose_tweet
    original_date = arrow.get(tweet["created_at"], "ddd MMM DD H:m:s Z YYYY", locale="en")
  File "C:\python37\lib\site-packages\arrow\api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "C:\python37\lib\site-packages\arrow\factory.py", line 263, in get
    return self.type(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'locale'

**Comment by manuelcortez** [comment]
Could you tell me what i the arrow version you are using?

**Comment by Mohamed00** [comment]
Using version 0.14.4.

**Comment by manuelcortez** [comment]
Could you give a try with 0.14.5 and tell me how it fails?

**Comment by Mohamed00** [comment]
It seems to work now, though I'm getting a warning.

C:\python37\lib\site-packages\arrow\factory.py:249: ArrowParseWarning: 
The .get() parsing method with a format string wi
ll parse more strictly in version 0.15.0.See 
https://github.com/crsmithdev/arrow/issues/612 for more details.
   ArrowParseWarning,

**Comment by Mohamed00** [comment]
It seems that I can't view tweets. Trying to view tweets shows this traceback.
Traceback (most recent call last):
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 72, in <lambda>
    self.parent.Bind(wx.EVT_HOTKEY, lambda evt: self.process_key(evt, key_id), id=key_id)
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 99, in process_key
    self.handle_key(i)
  File "C:\twblue\src\keyboard_handler\main.py", line 47, in handle_key
    return function()
  File "C:\twblue\src\controller\mainController.py", line 807, in view_item
    msg = messages.viewTweet(tweet, tweetsList, utc_offset=buffer.session.db["utc_offset"])
  File "C:\twblue\src\controller\messages.py", line 240, in __init__
    date = original_date.replace(seconds=utc_offset).format(_(u"MMM D, YYYY. H:m"), locale=languageHandler.getLanguage()
)
  File "C:\python37\lib\site-packages\arrow\arrow.py", line 590, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "seconds"

**Comment by systemcatch** [comment]
Hey @Mohamed00 there was a regression bug in arrow 0.14.4 which would cause ```original_date = arrow.get(tweet["created_at"], "ddd MMM DD HMs Z YYYY", locale="en")``` to fail. If you upgrade to 0.14.5 the bug is fixed.

**Comment by manuelcortez** [comment]
Hey @Mohamed00 , could you give a try now? I have muted the arrow warnings in V0.14.x versions (will remove the code when 0.15 is released) and fixed the display tweet dialog.

**Comment by Mohamed00** [comment]
Yep, it's working now, tweets are displaying properly.

**Comment by Mohamed00** [comment]
It seems the traceback is still occurring when viewing direct messages.
