### ISSUE TITLE
Retweeted quoted long tweets not expanded in the view tweet dialog

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#333]
### Steps to reproduce.
1. Post a tweet.
2. Quote the tweet with something longer than 140 characters.
3. Retweet the quoted tweet and display the retweet in the view tweet dialog.
### Expected.
The retweet should be expanded as it is in the graphical and invisible interfaces.
### Actual.
The retweet is not expanded.

**Comment by manuelcortez** [comment]
This should be fixed on #365

**Comment by Mohamed00** [comment]
Hi, it doesn't seem to be fixed completely. I just tested with a retweeted quoted tweet that is longer than 140 characters, and while the bug that occurred in the graphical and invisible interfaces is fixed, this particular one still isn't.
